name: Fetch and Commit Onion Details

on:
  workflow_dispatch:
  
jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch File
      run: curl -o t_details https://onionoo.torproject.org/details

    - name: Commit and Push if changes
      run: |
        git config --global user.email "jjewitt1@gmail.com"
        git config --global user.name "J Jewitt"
        git add tor_details.txt
        git commit -m "Update file" || echo "No changes to commit"
        git push
